# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='note', max_length=20),
        ),
    ]
