# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('des', models.CharField(max_length=400)),
                ('img_url', models.URLField()),
            ],
            options={
                'ordering': ('-pub_time',),
            },
        ),
    ]
