# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20171126_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='github_url',
            field=models.URLField(default='https://github.com/bai3'),
        ),
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(default='http://39.108.84.239/'),
        ),
    ]
