# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20171126_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名和')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='用户邮箱')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='注册手机号码')),
                ('rank', models.CharField(choices=[('1', '普通会员'), ('2', 'VIP会员'), ('3', 'SVIP会员'), ('4', '管理员'), ('5', '站长')], default='1', max_length=2, verbose_name='会员等级')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
    ]
