# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='文章标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(default='note', max_length=20, verbose_name='文章类别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='work',
            name='des',
            field=models.CharField(max_length=400, verbose_name='作品描述'),
        ),
        migrations.AlterField(
            model_name='work',
            name='github_url',
            field=models.URLField(default='https://github.com/bai3', verbose_name='github地址'),
        ),
        migrations.AlterField(
            model_name='work',
            name='img_url',
            field=models.URLField(verbose_name='作品展示图片地址'),
        ),
        migrations.AlterField(
            model_name='work',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=100, verbose_name='作品标题'),
        ),
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.URLField(default='http://39.108.84.239/', verbose_name='项目地址'),
        ),
    ]
