# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(default='', max_length=20, verbose_name='留言人'),
        ),
    ]
