# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20171215_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200, verbose_name='留言内容'),
        ),
    ]
